name 'wrap_java'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures wrap_java'
long_description 'Installs/Configures wrap_java'
depends 'java'
version '0.1.0'
